version: '3'
services:
  mencari-mbak-lea:
    build: .
    ports:
      - "9999:1337"
    environment:
      - FLAG=VincooCTF{Congrats!_sekarang_kamu_belajar_Lightweight_Encryption_Algorithm}
      - PYTHONUNBUFFERED=1
    restart: always
